name: cv_maker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  custom_navigation_bar: ^0.8.2
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.7
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  pdf: ^3.10.6
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  styled_text: ^8.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.23.0

  
flutter_gen:

  output: lib/utils/constants/
  line_length: 120

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

